export interface SkillDefinition {
  name: string;
  aliases: string[];
}

export const SKILLS_LIST: SkillDefinition[] = [
  { name: 'JavaScript', aliases: ['JavaScript'] },
  { name: 'TypeScript', aliases: ['TypeScript', 'TS'] },
  { name: 'Python', aliases: ['Python'] },
  { name: 'Java', aliases: ['Java'] },
  { name: 'C++', aliases: ['C++'] },
  { name: 'C#', aliases: ['C#'] },
  { name: 'React', aliases: ['React', 'React.js', 'ReactJS'] },
  { name: 'Next.js', aliases: ['Next.js', 'NextJS'] },
  { name: 'Vue.js', aliases: ['Vue.js', 'VueJS', 'Vue'] },
  { name: 'Angular', aliases: ['Angular', 'AngularJS'] },
  { name: 'Node.js', aliases: ['Node.js', 'NodeJS', 'Node'] },
  { name: 'NestJS', aliases: ['NestJS', 'Nest.js'] },
  { name: 'Express', aliases: ['Express', 'Express.js'] },
  { name: 'REST APIs', aliases: ['REST API', 'REST APIs', 'RESTful'] },
  { name: 'GraphQL', aliases: ['GraphQL'] },
  { name: 'PostgreSQL', aliases: ['PostgreSQL', 'Postgres'] },
  { name: 'MySQL', aliases: ['MySQL'] },
  { name: 'MongoDB', aliases: ['MongoDB', 'Mongo'] },
  { name: 'Redis', aliases: ['Redis'] },
  { name: 'SQL', aliases: ['SQL'] },
  { name: 'Prisma', aliases: ['Prisma'] },
  { name: 'AWS', aliases: ['AWS', 'Amazon Web Services'] },
  { name: 'Azure', aliases: ['Azure'] },
  { name: 'Google Cloud', aliases: ['Google Cloud', 'GCP'] },
  { name: 'Docker', aliases: ['Docker'] },
  { name: 'Kubernetes', aliases: ['Kubernetes', 'K8s'] },
  { name: 'Git', aliases: ['Git'] },
  { name: 'GitHub Actions', aliases: ['GitHub Actions'] },
  { name: 'CI/CD', aliases: ['CI/CD', 'CI-CD'] },
  { name: 'Linux', aliases: ['Linux'] },
  { name: 'HTML', aliases: ['HTML', 'HTML5'] },
  { name: 'CSS', aliases: ['CSS', 'CSS3'] },
  { name: 'Tailwind CSS', aliases: ['Tailwind', 'Tailwind CSS', 'TailwindCSS'] },
  { name: 'Jest', aliases: ['Jest'] },
  { name: 'Vitest', aliases: ['Vitest'] },
  { name: 'Cypress', aliases: ['Cypress'] },
  { name: 'Playwright', aliases: ['Playwright'] },
  { name: 'JWT', aliases: ['JWT', 'JSON Web Token'] },
  { name: 'OAuth', aliases: ['OAuth'] },
  { name: 'Machine Learning', aliases: ['Machine Learning', 'ML'] },
  { name: 'TensorFlow', aliases: ['TensorFlow'] },
  { name: 'PyTorch', aliases: ['PyTorch'] },
  { name: 'Pandas', aliases: ['Pandas'] },
  { name: 'NumPy', aliases: ['NumPy'] },
  { name: 'Scikit-learn', aliases: ['Scikit-learn', 'sklearn'] },
  { name: 'Agile', aliases: ['Agile', 'Scrum'] },
  { name: 'Flask', aliases: ['Flask'] },
  { name: 'FastAPI', aliases: ['FastAPI'] },
  { name: 'Django', aliases: ['Django'] },
  { name: '.NET', aliases: ['.NET', 'ASP.NET', 'dotnet'] },
  { name: 'Entity Framework', aliases: ['Entity Framework', 'EF Core'] },
];